// Generated by build_web_test.py -- do not edit by hand.
const CLIPS = [
  {
    "id": "c01",
    "stimuli": [
      "6d0a3e54",
      "d6c6dfd0",
      "7d4e6d97",
      "24a432ab",
      "46ee414a",
      "cc349650"
    ]
  },
  {
    "id": "c02",
    "stimuli": [
      "d0e63574",
      "e14e7969",
      "9f263b08",
      "72f8e1b4",
      "1a0eb28b",
      "d267a8ef"
    ]
  },
  {
    "id": "c03",
    "stimuli": [
      "8b4c0208",
      "54e763a4",
      "efebbe90",
      "2a4c088b",
      "7efaa816",
      "77b5b2d3"
    ]
  },
  {
    "id": "c04",
    "stimuli": [
      "3c3a1389",
      "a0569ed4",
      "69c1a51c",
      "41614482",
      "84790962",
      "a7fb2358"
    ]
  },
  {
    "id": "c05",
    "stimuli": [
      "de5dde2a",
      "d4a09081",
      "93a19b1a",
      "6848eae8",
      "024773ca",
      "5f6d7688"
    ]
  },
  {
    "id": "c06",
    "stimuli": [
      "923d737a",
      "d14a99ff",
      "ff721b96",
      "b556111f",
      "ca4b9894",
      "4fe05537"
    ]
  },
  {
    "id": "c07",
    "stimuli": [
      "1cac54b6",
      "a8af6d73",
      "408e9bf1",
      "2901ce22",
      "5c26ddbf",
      "ec45a0e7"
    ]
  },
  {
    "id": "c08",
    "stimuli": [
      "7de3d740",
      "5f191696",
      "79a29b37",
      "2fe56207",
      "a5075620",
      "d13759cd"
    ]
  }
];
